apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-app
  annotations:
    github.com/project-slug: hwakabh/backstage-app
spec:
  type: other
  lifecycle: unknown
  owner: guests
